// Issues and discussions: in-repo, ref-tracked, signable.
//
// Storage model
// =============
// Each issue or discussion lives at a single ref: `refs/issues/<N>`.
// The ref points to a blob whose payload is the TOML-encoded current
// state (header + ordered events). Updates are write-the-whole-blob,
// serialized through `repo.lock()`.
//
// Why ref-to-blob and not commit-history-per-issue:
//
//   - The wire protocol already pushes/pulls every ref under refs/, so
//     ref-to-blob travels with `clone`, `fetch`, and `push` with no
//     protocol changes.
//   - The reflog already records every ref movement, so a per-issue
//     history is available via `gyt reflog refs/issues/<N>` without us
//     needing a parallel event store.
//   - Loose objects are content-addressed; identical states deduplicate
//     for free across forks.
//   - One ref → one blob keeps reads O(1) and writes O(state size). For
//     large discussions we revisit this, but XZ on the wire and on disk
//     makes the "rewrite the whole TOML on every comment" model cheap.
//
// Format (TOML)
// =============
// The blob payload is canonical TOML — we hand-serialize so that two
// runs that produce the same logical state produce byte-identical
// blobs (important for dedup and for clean diffs in `gyt reflog`):
//
//     # generated by gyt; canonical ordering matters
//     schema_version = 1
//     kind = "issue"          # or "discussion"
//     number = 42
//     title = "..."
//     state = "open"          # or "closed"
//     author = "Name <email>"
//     created_ts = 1715000000
//     labels = ["bug", "p1"]
//     assignees = ["Name <email>", ...]
//     mentions = [12, 13]     # other issue numbers referenced in any body
//
//     [[event]]
//     kind = "open"
//     author = "Name <email>"
//     ts = 1715000000
//     body = "..."
//
//     [[event]]
//     kind = "comment"
//     author = "Name <email>"
//     ts = 1715000100
//     body = "..."
//
//     [[event]]
//     kind = "label"
//     author = "Name <email>"
//     ts = 1715000200
//     add = ["bug"]
//     remove = []
//
//     [[event]]
//     kind = "assign"
//     author = "Name <email>"
//     ts = 1715000300
//     add = ["Name <email>"]
//     remove = []
//
//     [[event]]
//     kind = "close"
//     author = "Name <email>"
//     ts = 1715001000
//     reason = "fixed in #44"
//
//     [[event]]
//     kind = "reopen"
//     author = "Name <email>"
//     ts = 1715002000
//
// The header fields (title, state, labels, …) are kept in sync with
// the event log so a reader doesn't have to fold events to render the
// current state. The fold is recomputed on every write.

use crate::errors::{GytError, Result};
use crate::fs_util;
use crate::hash::ObjectId;
use crate::object;
use crate::object::ObjectKind;
use crate::refs;
use crate::repo::Repo;
use std::fmt::Write as _;
use std::path::Path;

pub const SCHEMA_VERSION: u32 = 1;
pub const ISSUE_REFS_PREFIX: &str = "refs/issues";
const COUNTER_PATH: &str = "meta/issues_next";

/// The whole on-disk representation of one issue or discussion.
#[derive(Debug, Clone)]
pub struct Issue {
    pub number: u64,
    pub kind: IssueKind,
    pub title: String,
    pub state: IssueState,
    pub author: String,
    pub created_ts: i64,
    pub labels: Vec<String>,
    pub assignees: Vec<String>,
    pub mentions: Vec<u64>,
    pub events: Vec<Event>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IssueKind {
    Issue,
    Discussion,
}

impl IssueKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Issue => "issue",
            Self::Discussion => "discussion",
        }
    }
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "issue" => Ok(Self::Issue),
            "discussion" => Ok(Self::Discussion),
            other => Err(GytError::Refs(format!("unknown issue kind: {other}"))),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IssueState {
    Open,
    Closed,
}

impl IssueState {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Closed => "closed",
        }
    }
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "open" => Ok(Self::Open),
            "closed" => Ok(Self::Closed),
            other => Err(GytError::Refs(format!("unknown issue state: {other}"))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Event {
    pub kind: EventKind,
    pub author: String,
    pub ts: i64,
    pub body: String,
    pub add: Vec<String>,
    pub remove: Vec<String>,
    pub reason: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventKind {
    Open,
    Comment,
    Close,
    Reopen,
    Label,
    Assign,
}

impl EventKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Comment => "comment",
            Self::Close => "close",
            Self::Reopen => "reopen",
            Self::Label => "label",
            Self::Assign => "assign",
        }
    }
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "open" => Ok(Self::Open),
            "comment" => Ok(Self::Comment),
            "close" => Ok(Self::Close),
            "reopen" => Ok(Self::Reopen),
            "label" => Ok(Self::Label),
            "assign" => Ok(Self::Assign),
            other => Err(GytError::Refs(format!("unknown event kind: {other}"))),
        }
    }
}

// ─── Encoding / decoding ──────────────────────────────────────────────

/// Encode an issue to canonical TOML bytes. Field ordering is fixed so
/// equivalent issues produce identical blobs.
#[expect(
    clippy::unwrap_used,
    reason = "writeln! to String never fails; the Result is only present for io::Write compatibility"
)]
pub fn encode(issue: &Issue) -> Vec<u8> {
    let mut s = String::new();
    s.push_str("# generated by gyt; canonical ordering matters\n");
    writeln!(s, "schema_version = {SCHEMA_VERSION}").unwrap();
    writeln!(s, "kind = {:?}", issue.kind.as_str()).unwrap();
    writeln!(s, "number = {}", issue.number).unwrap();
    writeln!(s, "title = {:?}", issue.title).unwrap();
    writeln!(s, "state = {:?}", issue.state.as_str()).unwrap();
    writeln!(s, "author = {:?}", issue.author).unwrap();
    writeln!(s, "created_ts = {}", issue.created_ts).unwrap();
    writeln!(s, "labels = {}", toml_string_array(&issue.labels)).unwrap();
    writeln!(s, "assignees = {}", toml_string_array(&issue.assignees)).unwrap();
    writeln!(s, "mentions = {}", toml_u64_array(&issue.mentions)).unwrap();
    s.push('\n');
    for e in &issue.events {
        s.push_str("[[event]]\n");
        writeln!(s, "kind = {:?}", e.kind.as_str()).unwrap();
        writeln!(s, "author = {:?}", e.author).unwrap();
        writeln!(s, "ts = {}", e.ts).unwrap();
        writeln!(s, "body = {:?}", e.body).unwrap();
        writeln!(s, "add = {}", toml_string_array(&e.add)).unwrap();
        writeln!(s, "remove = {}", toml_string_array(&e.remove)).unwrap();
        writeln!(s, "reason = {:?}", e.reason).unwrap();
        s.push('\n');
    }
    s.into_bytes()
}

/// Decode an issue from a TOML blob. The parser is hand-rolled — we
/// don't add a TOML dependency. The format is restricted enough that a
/// straight line scan handles every encode() output, and any malformed
/// input is rejected with a clean error rather than panicking.
pub fn decode(bytes: &[u8]) -> Result<Issue> {
    let text = std::str::from_utf8(bytes)
        .map_err(|_| GytError::Refs("issue blob is not valid utf-8".into()))?;

    let mut number: Option<u64> = None;
    let mut kind: Option<IssueKind> = None;
    let mut title = String::new();
    let mut state: Option<IssueState> = None;
    let mut author = String::new();
    let mut created_ts: i64 = 0;
    let mut labels: Vec<String> = Vec::new();
    let mut assignees: Vec<String> = Vec::new();
    let mut mentions: Vec<u64> = Vec::new();
    let mut schema_seen = false;

    let mut events: Vec<Event> = Vec::new();
    let mut cur: Option<Event> = None;

    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "[[event]]" {
            if let Some(e) = cur.take() {
                events.push(e);
            }
            cur = Some(Event {
                kind: EventKind::Comment,
                author: String::new(),
                ts: 0,
                body: String::new(),
                add: Vec::new(),
                remove: Vec::new(),
                reason: String::new(),
            });
            continue;
        }
        let (key, val) = line
            .split_once('=')
            .ok_or_else(|| GytError::Refs(format!("issue blob: malformed line: {raw}")))?;
        let key = key.trim();
        let val = val.trim();
        if let Some(e) = cur.as_mut() {
            match key {
                "kind" => e.kind = EventKind::parse(&parse_toml_string(val)?)?,
                "author" => e.author = parse_toml_string(val)?,
                "ts" => e.ts = val.parse::<i64>().map_err(|_| invalid("event.ts"))?,
                "body" => e.body = parse_toml_string(val)?,
                "add" => e.add = parse_toml_string_array(val)?,
                "remove" => e.remove = parse_toml_string_array(val)?,
                "reason" => e.reason = parse_toml_string(val)?,
                other => return Err(invalid(&format!("unknown event field: {other}"))),
            }
        } else {
            match key {
                "schema_version" => {
                    let v: u32 = val.parse().map_err(|_| invalid("schema_version"))?;
                    if v != SCHEMA_VERSION {
                        return Err(GytError::Refs(format!(
                            "unsupported issue schema_version {v}"
                        )));
                    }
                    schema_seen = true;
                }
                "kind" => kind = Some(IssueKind::parse(&parse_toml_string(val)?)?),
                "number" => number = Some(val.parse().map_err(|_| invalid("number"))?),
                "title" => title = parse_toml_string(val)?,
                "state" => state = Some(IssueState::parse(&parse_toml_string(val)?)?),
                "author" => author = parse_toml_string(val)?,
                "created_ts" => {
                    created_ts = val.parse::<i64>().map_err(|_| invalid("created_ts"))?;
                }
                "labels" => labels = parse_toml_string_array(val)?,
                "assignees" => assignees = parse_toml_string_array(val)?,
                "mentions" => mentions = parse_toml_u64_array(val)?,
                other => return Err(invalid(&format!("unknown issue field: {other}"))),
            }
        }
    }
    if let Some(e) = cur.take() {
        events.push(e);
    }
    if !schema_seen {
        return Err(invalid("missing schema_version"));
    }
    let number = number.ok_or_else(|| invalid("missing number"))?;
    let kind = kind.ok_or_else(|| invalid("missing kind"))?;
    let state = state.ok_or_else(|| invalid("missing state"))?;
    Ok(Issue {
        number,
        kind,
        title,
        state,
        author,
        created_ts,
        labels,
        assignees,
        mentions,
        events,
    })
}

fn invalid(field: &str) -> GytError {
    GytError::Refs(format!("issue blob: invalid {field}"))
}

fn toml_string_array(xs: &[String]) -> String {
    if xs.is_empty() {
        return "[]".into();
    }
    let parts: Vec<String> = xs.iter().map(|s| format!("{s:?}")).collect();
    format!("[{}]", parts.join(", "))
}

fn toml_u64_array(xs: &[u64]) -> String {
    if xs.is_empty() {
        return "[]".into();
    }
    let parts: Vec<String> = xs.iter().map(u64::to_string).collect();
    format!("[{}]", parts.join(", "))
}
#[expect(
    clippy::string_slice,
    reason = "byte offsets used are at ASCII / char-boundary positions by construction"
)]
fn parse_toml_string(s: &str) -> Result<String> {
    // Accept ONLY a literal `"..."` form using Rust's debug formatting
    // (\\, \", \n, \r, \t). No multi-line strings, no raw strings, no
    // bare keys — the encoder never emits those.
    let s = s.trim();
    if s.len() < 2 || !s.starts_with('"') || !s.ends_with('"') {
        return Err(GytError::Refs(format!("issue blob: not a quoted string: {s}")));
    }
    let inner = &s[1..s.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut iter = inner.chars();
    while let Some(c) = iter.next() {
        if c == '\\' {
            match iter.next() {
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                Some('t') => out.push('\t'),
                Some('\\') => out.push('\\'),
                Some('"') => out.push('"'),
                Some('0') => out.push('\0'),
                Some(other) => {
                    return Err(GytError::Refs(format!(
                        "issue blob: unsupported escape \\{other}"
                    )));
                }
                None => return Err(GytError::Refs("issue blob: trailing backslash".into())),
            }
        } else {
            out.push(c);
        }
    }
    Ok(out)
}
#[expect(
    clippy::string_slice,
    reason = "byte offsets used are at ASCII / char-boundary positions by construction"
)]
fn parse_toml_string_array(s: &str) -> Result<Vec<String>> {
    let s = s.trim();
    if s == "[]" {
        return Ok(Vec::new());
    }
    if !s.starts_with('[') || !s.ends_with(']') {
        return Err(GytError::Refs(format!("issue blob: not an array: {s}")));
    }
    let inner = &s[1..s.len() - 1];
    let mut out = Vec::new();
    let mut buf = String::new();
    let mut in_str = false;
    let mut escape = false;
    for c in inner.chars() {
        if escape {
            buf.push(c);
            escape = false;
            continue;
        }
        if in_str {
            buf.push(c);
            if c == '\\' {
                escape = true;
            } else if c == '"' {
                in_str = false;
            }
            continue;
        }
        if c == '"' {
            buf.push(c);
            in_str = true;
        } else if c == ',' {
            out.push(parse_toml_string(buf.trim())?);
            buf.clear();
        } else if !c.is_whitespace() {
            buf.push(c);
        }
    }
    if !buf.trim().is_empty() {
        out.push(parse_toml_string(buf.trim())?);
    }
    Ok(out)
}
#[expect(
    clippy::string_slice,
    reason = "byte offsets used are at ASCII / char-boundary positions by construction"
)]
fn parse_toml_u64_array(s: &str) -> Result<Vec<u64>> {
    let s = s.trim();
    if s == "[]" {
        return Ok(Vec::new());
    }
    if !s.starts_with('[') || !s.ends_with(']') {
        return Err(GytError::Refs(format!("issue blob: not an array: {s}")));
    }
    let inner = &s[1..s.len() - 1];
    let mut out = Vec::new();
    for tok in inner.split(',') {
        let t = tok.trim();
        if t.is_empty() {
            continue;
        }
        out.push(t.parse::<u64>().map_err(|_| invalid("u64 in array"))?);
    }
    Ok(out)
}

// ─── Storage ───────────────────────────────────────────────────────────

/// Atomically allocate the next issue number. Caller must already hold
/// `repo.lock()`; we don't take it ourselves because most callers want
/// to allocate + write the issue under one critical section.
pub fn next_number_locked(repo: &Repo) -> Result<u64> {
    let p = repo.gyt_dir.join(COUNTER_PATH);
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let next: u64 = if p.exists() {
        let body = fs_util::read_all(&p)?;
        let txt = std::str::from_utf8(&body)
            .map_err(|_| GytError::Refs("issues_next is not utf-8".into()))?;
        txt.trim()
            .parse::<u64>()
            .map_err(|_| GytError::Refs("issues_next is not a number".into()))?
    } else {
        1
    };
    // L16: checked_add so a counter at u64::MAX doesn't panic in debug
    // (test runner) or wrap silently in release.
    let bumped = next.checked_add(1).ok_or_else(|| {
        GytError::Refs("issues_next counter overflow (u64::MAX)".into())
    })?;
    fs_util::atomic_write(&p, format!("{bumped}\n").as_bytes())?;
    Ok(next)
}

/// Validate that `new` is a legitimate monotonic-append update to
/// `old`. Closes C3/F-D8-02: previously the wire path accepted any
/// `refs/issues/<N>` blob, so an rw client could push a blob with
/// `events = []` and silently erase the entire issue history. Now we
/// require:
///
/// - same `number`, `kind`, `created_ts`, `author`, `title` (header
///   fields can never change after creation), and
/// - `new.events` is a prefix-extension of `old.events` (existing
///   events are byte-for-byte preserved, only new events appended).
///
/// `state` and `labels`/`assignees`/`mentions` MAY change between
/// versions (closing an issue / adding a label is a legitimate
/// update); those don't need a matching event today.
pub fn validate_extends(old: &Issue, new: &Issue) -> Result<()> {
    if new.number != old.number {
        return Err(GytError::Refs(format!(
            "issue rewind: number changed {} -> {}",
            old.number, new.number
        )));
    }
    if new.kind != old.kind {
        return Err(GytError::Refs("issue rewind: kind changed".into()));
    }
    if new.created_ts != old.created_ts {
        return Err(GytError::Refs("issue rewind: created_ts changed".into()));
    }
    if new.author != old.author {
        return Err(GytError::Refs("issue rewind: author changed".into()));
    }
    if new.title != old.title {
        return Err(GytError::Refs("issue rewind: title changed".into()));
    }
    if new.events.len() < old.events.len() {
        return Err(GytError::Refs(format!(
            "issue rewind: event count decreased {} -> {}",
            old.events.len(),
            new.events.len()
        )));
    }
    for (i, oe) in old.events.iter().enumerate() {
        // Length already validated above so .get is Some.
        if new.events.get(i) != Some(oe) {
            return Err(GytError::Refs(format!(
                "issue rewind: event #{i} was modified"
            )));
        }
    }
    // B4: timestamps must be non-decreasing across the chain. Without
    // this, a client can push events with `ts = 0` or with ts going
    // backwards, and the renderer (which orders by file position, not
    // timestamp) shows them in the wrong order. The check is non-strict
    // — same-second events are legitimate (a script can `gyt issue
    // comment` twice within the same wall-clock second).
    for w in new.events.windows(2) {
        if let [a, b] = w
            && b.ts < a.ts
        {
            return Err(GytError::Refs(format!(
                "issue event ts not monotonic: {} -> {}",
                a.ts, b.ts
            )));
        }
    }
    Ok(())
}

pub fn ref_name(n: u64) -> String {
    format!("{ISSUE_REFS_PREFIX}/{n}")
}

/// Read the issue stored at refs/issues/<n>. Returns NotFound if the
/// ref doesn't exist, regardless of whether the underlying blob is
/// present in the object store (a missing blob is a hard error worth
/// surfacing).
pub fn read(repo: &Repo, n: u64) -> Result<Issue> {
    let id = match refs::read_ref(&repo.gyt_dir, &ref_name(n)) {
        Ok(id) => id,
        Err(GytError::Refs(_)) => return Err(GytError::NotFound(format!("issue #{n}"))),
        Err(e) => return Err(e),
    };
    let iss = read_blob(&repo.gyt_dir, &id)?;
    // L17: cross-check the on-disk blob's `number` field against the
    // ref's N. A malicious / corrupted push could otherwise point
    // refs/issues/5 at a blob claiming `number = 99`, and `gyt issue
    // show 5` would print "#99".
    if iss.number != n {
        return Err(GytError::Refs(format!(
            "issue blob at refs/issues/{n} claims number={}", iss.number
        )));
    }
    Ok(iss)
}

fn read_blob(repo_gyt: &Path, id: &ObjectId) -> Result<Issue> {
    let obj = object::store::read(repo_gyt, id)?;
    if obj.kind != ObjectKind::Blob {
        return Err(GytError::Refs(format!(
            "refs/issues blob expected, found {}",
            obj.kind.as_str()
        )));
    }
    decode(&obj.payload)
}

/// Write an issue's full state. Returns the new blob id. Caller must
/// hold `repo.lock()` to prevent concurrent writers from interleaving
/// updates.
pub fn write_locked(repo: &Repo, issue: &Issue) -> Result<ObjectId> {
    let bytes = encode(issue);
    let id = object::store::write_bytes(&repo.gyt_dir, ObjectKind::Blob, &bytes)?;
    refs::write_ref(&repo.gyt_dir, &ref_name(issue.number), &id)?;
    Ok(id)
}

/// List all issues (open + closed) in ascending number order.
pub fn list(repo: &Repo) -> Result<Vec<Issue>> {
    let refs_ = refs::list_refs(&repo.gyt_dir, ISSUE_REFS_PREFIX)?;
    let mut out = Vec::with_capacity(refs_.len());
    for (name, id) in refs_ {
        // The ref-walker may yield names like `refs/issues/12`; skip
        // anything that doesn't parse as a number, so a future
        // sub-namespace (`refs/issues/meta/...`) can't crash listing.
        let Some(_n_str) = name.strip_prefix(&format!("{ISSUE_REFS_PREFIX}/")) else {
            continue;
        };
        // A corrupt single issue should not break `list`. Skip and let
        // `gyt issue show <N>` surface the real error.
        if let Ok(i) = read_blob(&repo.gyt_dir, &id) {
            out.push(i);
        }
    }
    out.sort_by_key(|i| i.number);
    Ok(out)
}

// ─── Helpers used by the CLI ──────────────────────────────────────────

/// Extract `#N` mentions from arbitrary text. Returns a sorted, deduped
/// list of issue numbers. A mention is a `#` followed by 1-10 digits,
/// not preceded by an alphanumeric character (so `abc#1` doesn't match
/// — that's almost certainly part of a longer token).
#[must_use]
#[expect(
    clippy::indexing_slicing,
    clippy::string_slice,
    reason = "args[i] / similar indexing is gated by an explicit bounds check on a preceding line; byte offsets used are at ASCII / char-boundary positions by construction"
)]
pub fn extract_mentions(text: &str) -> Vec<u64> {
    let bytes = text.as_bytes();
    let mut out: Vec<u64> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'#'
            && (i == 0 || !is_word_char(bytes[i - 1]))
            && i + 1 < bytes.len()
            && bytes[i + 1].is_ascii_digit()
        {
            let mut j = i + 1;
            while j < bytes.len() && j - i <= 11 && bytes[j].is_ascii_digit() {
                j += 1;
            }
            // Require a non-word terminator (or EOF) to rule out `#1abc`.
            if (j == bytes.len() || !is_word_char(bytes[j]))
                && let Ok(n) = text[i + 1..j].parse::<u64>()
            {
                out.push(n);
            }
            i = j;
        } else {
            i += 1;
        }
    }
    out.sort_unstable();
    out.dedup();
    out
}

const fn is_word_char(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// Merge new mentions into the issue's mentions list, keeping order
/// sorted and deduplicated.
pub fn merge_mentions(into: &mut Vec<u64>, new: &[u64], self_number: u64) {
    for n in new {
        if *n == self_number {
            continue;
        }
        if !into.contains(n) {
            into.push(*n);
        }
    }
    into.sort_unstable();
    into.dedup();
}

#[cfg(test)]
mod tests {
    #![expect(
        clippy::unwrap_used,
        reason = "test code: panicking on unexpected input is how a test signals failure"
    )]
    use super::*;

    fn fixture() -> Issue {
        Issue {
            number: 42,
            kind: IssueKind::Issue,
            title: "Bug in X".into(),
            state: IssueState::Open,
            author: "Alice <a@x>".into(),
            created_ts: 1_715_000_000,
            labels: vec!["bug".into(), "p1".into()],
            assignees: vec!["Bob <b@x>".into()],
            mentions: vec![12, 13],
            events: vec![
                Event {
                    kind: EventKind::Open,
                    author: "Alice <a@x>".into(),
                    ts: 1_715_000_000,
                    body: "It crashes when…\nthe quote is \"problem\"".into(),
                    add: vec![],
                    remove: vec![],
                    reason: String::new(),
                },
                Event {
                    kind: EventKind::Comment,
                    author: "Bob <b@x>".into(),
                    ts: 1_715_000_050,
                    body: "Look at this: #44, also #13".into(),
                    add: vec![],
                    remove: vec![],
                    reason: String::new(),
                },
                Event {
                    kind: EventKind::Label,
                    author: "Bob <b@x>".into(),
                    ts: 1_715_000_100,
                    body: String::new(),
                    add: vec!["bug".into()],
                    remove: vec![],
                    reason: String::new(),
                },
                Event {
                    kind: EventKind::Close,
                    author: "Bob <b@x>".into(),
                    ts: 1_715_001_000,
                    body: String::new(),
                    add: vec![],
                    remove: vec![],
                    reason: "fixed in #44".into(),
                },
            ],
        }
    }

    #[test]
    fn round_trip_preserves_every_field() {
        let issue = fixture();
        let bytes = encode(&issue);
        let back = decode(&bytes).unwrap();
        assert_eq!(back.number, issue.number);
        assert_eq!(back.title, issue.title);
        assert_eq!(back.state, issue.state);
        assert_eq!(back.kind, issue.kind);
        assert_eq!(back.author, issue.author);
        assert_eq!(back.created_ts, issue.created_ts);
        assert_eq!(back.labels, issue.labels);
        assert_eq!(back.assignees, issue.assignees);
        assert_eq!(back.mentions, issue.mentions);
        assert_eq!(back.events.len(), issue.events.len());
        for (a, b) in back.events.iter().zip(issue.events.iter()) {
            assert_eq!(a.kind, b.kind);
            assert_eq!(a.author, b.author);
            assert_eq!(a.ts, b.ts);
            assert_eq!(a.body, b.body);
            assert_eq!(a.add, b.add);
            assert_eq!(a.remove, b.remove);
            assert_eq!(a.reason, b.reason);
        }
    }

    #[test]
    fn encoded_form_is_byte_canonical() {
        let a = encode(&fixture());
        let b = encode(&decode(&a).unwrap());
        assert_eq!(a, b, "decode(encode(x)) must re-encode bit-identically");
    }

    #[test]
    fn malformed_blob_returns_error_not_panic() {
        assert!(decode(b"not even toml").is_err());
        assert!(decode(b"schema_version = 999\n").is_err());
        assert!(decode(b"schema_version = 1\nnumber = notanumber\n").is_err());
    }

    #[test]
    fn extract_mentions_handles_edge_cases() {
        assert_eq!(extract_mentions("see #1, #2 and #3"), vec![1, 2, 3]);
        assert_eq!(extract_mentions("#42"), vec![42]);
        assert_eq!(extract_mentions("no mentions here"), Vec::<u64>::new());
        // Not preceded by word character → match
        assert_eq!(extract_mentions("(#5)"), vec![5]);
        // Preceded by alphanumeric → no match
        assert_eq!(extract_mentions("abc#5"), Vec::<u64>::new());
        // Trailing digits then letter → no match
        assert_eq!(extract_mentions("#5abc"), Vec::<u64>::new());
        // Dedupe
        assert_eq!(extract_mentions("#1 and #1"), vec![1]);
        // Hash but no digits
        assert_eq!(extract_mentions("# this is a comment"), Vec::<u64>::new());
        // Sort
        let mut got = extract_mentions("#3 #1 #2");
        got.sort_unstable();
        assert_eq!(got, vec![1, 2, 3]);
    }

    #[test]
    fn extract_mentions_ignores_self_reference() {
        let mut m = vec![12u64];
        merge_mentions(&mut m, &[42, 13, 12], 42);
        assert_eq!(m, vec![12, 13]); // 42 (self) dropped, 12 dedupes
    }

    // ── B4: ts monotonicity in validate_extends ──────────────────

    #[test]
    fn validate_extends_rejects_non_monotonic_appended_event() {
        // Append an event whose ts is BEFORE the most-recent existing
        // event's ts. The prefix-equality check still passes, but the
        // monotonicity check must catch the inversion.
        let old = fixture();
        let mut new = old.clone();
        new.events.push(Event {
            kind: EventKind::Comment,
            author: "Mallory <m@x>".into(),
            ts: 100, // way before any prior event's ts
            body: "ts forged backward".into(),
            add: vec![],
            remove: vec![],
            reason: String::new(),
        });
        let err = validate_extends(&old, &new).unwrap_err();
        assert!(
            matches!(&err, GytError::Refs(m) if m.contains("ts not monotonic")),
            "expected Refs(ts not monotonic ...), got: {err:?}"
        );
    }

    #[test]
    fn validate_extends_accepts_same_second_appended_event() {
        // Same-second appends are legitimate; the check is non-strict.
        let old = fixture();
        let mut new = old.clone();
        let last_ts = new.events.last().unwrap().ts;
        new.events.push(Event {
            kind: EventKind::Comment,
            author: "Bob <b@x>".into(),
            ts: last_ts, // identical ts
            body: "same second is fine".into(),
            add: vec![],
            remove: vec![],
            reason: String::new(),
        });
        validate_extends(&old, &new).unwrap();
    }

    #[test]
    fn validate_extends_rejects_zero_ts_after_real_event() {
        // A `ts = 0` event after a real one is the simplest attack
        // ("erase visible chronology"). Must be rejected.
        let old = fixture();
        let mut new = old.clone();
        new.events.push(Event {
            kind: EventKind::Comment,
            author: "Mallory <m@x>".into(),
            ts: 0,
            body: "zeroed ts".into(),
            add: vec![],
            remove: vec![],
            reason: String::new(),
        });
        assert!(validate_extends(&old, &new).is_err());
    }
}
